# Generated by Django 5.0 on 2025-02-19 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100, verbose_name='Nome do Banco')),
                ('account_number', models.CharField(max_length=20, verbose_name='Número da Conta')),
                ('manager_name', models.CharField(max_length=100, verbose_name='Nome do Gerente')),
                ('manager_contact', models.CharField(max_length=100, verbose_name='Contato do Gerente')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Conta Bancária',
                'verbose_name_plural': 'Contas Bancárias',
                'ordering': ['bank_name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
                ('document', models.CharField(max_length=50, verbose_name='Documento')),
                ('description', models.CharField(max_length=200, verbose_name='Descrição')),
                ('transaction_type', models.CharField(choices=[('C', 'Crédito'), ('D', 'Débito')], max_length=1, verbose_name='Tipo')),
                ('value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.bankaccount', verbose_name='Conta')),
            ],
            options={
                'verbose_name': 'Transação',
                'verbose_name_plural': 'Transações',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
